### ISSUE TITLE
Bug dopo ultimo aggiornamento

### ISSUE THREAD

**Issue by gmansillo** [jacopoRufini/SO2Quiz#6]
Nell'ultima versione (quella con il timer, fantastico!) il programma si blocca e non è possibile procedere
![2018-06-11-200946_1366x768_scrot](https://user-images.githubusercontent.com/11967003/41249121-6b073de0-6db3-11e8-83e1-dfff5db48668.png)

Andando a capo si continua a visualizzare il timer anzichè la domanda successiva

JDK: 1.8.0_171
OS: Lubuntu x64

**Comment by jacopoRufini** [comment]
Si ho notato anche io.. ho chiesto al ragazzo che ha implementato il timer se può dare un'occhiata

**Comment by caciolai** [comment]
Ho fixato le parti di codice più losche, in diverse run che ho fatto non mi dà problemi, ora carico il tutto e apro una pull request, fatemi sapere!
